### PR TITLE
lotta styles & seatselection html & heading edits to all files

### PR DESCRIPTION
**Pull request by abigailboyer**
i edited the headings to all the pages so that the styling would be more consistent so before you approve and pull this, make sure all ur stuff is gucci otherwise ur gonna fuck up all ur files

just to be clear, i made the styling more consistent by making all of the `<header>` tags have the same contents and i made all of the secondary headings `<h2> ` with the appropriate titles. some things i changed to `<h3> `if they were also subheadings so review those changes so you understand themThanks

### CODE REVIEW

**Review by davonab — COMMENTED** [review]
Everything looks fine, I think you deleted the id's I put for some headers. I was using those to append error messages to the page.

**Comment by abigailboyer** [comment]
it's all good now can i merge it i think i can

**Comment by abigailboyer** [comment]
shti fuck

**Comment by abigailboyer** [comment]
shti fuck

**Review by Eirizarr — APPROVED** [review]

**Pull request merged**
